[32m2024-09-24 20:05:03 +0200[0m - dagster - [34mDEBUG[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - 43091 - LOGS_CAPTURED - Started capturing logs in process (pid: 43091).
[32m2024-09-24 20:05:03 +0200[0m - dagster - [34mDEBUG[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - 43091 - export_report - STEP_START - Started execution of step "export_report".
[32m2024-09-24 20:05:03 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Starting SodaAPI to Redshift Tables.....
[32m2024-09-24 20:05:04 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Fetching all datasets on page: 0
[32m2024-09-24 20:05:04 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Fetching all datasets on page: 1
[32m2024-09-24 20:05:05 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Fetching all datasets on page: 2
[32m2024-09-24 20:05:05 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Fetching all datasets on page: 3
[32m2024-09-24 20:05:06 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - export_report - Fetching all checks on page 0
[32m2024-09-24 20:05:13 +0200[0m - dagster - [34mERROR[0m - [31mprod_pipeline - 35ac8e2d-8b32-4f11-8e53-8c5bc64cd54f - 43091 - export_report - STEP_FAILURE - Execution of step "export_report" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "export_report"::

psycopg2.errors.StringDataRightTruncation: value too long for type character varying(500)


Stack Trace:
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/dbt-project/dagster/pipeline/exportapi.py", line 271, in export_report
    insert_into_table(conn, df_checks, checks_table)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/dbt-project/dagster/pipeline/exportapi.py", line 237, in insert_into_table
    cur.execute(insert_query, row)
[0m
