[32m2024-09-24 12:03:07 +0200[0m - dagster - [34mDEBUG[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - 26231 - LOGS_CAPTURED - Started capturing logs in process (pid: 26231).
[32m2024-09-24 12:03:07 +0200[0m - dagster - [34mDEBUG[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - 26231 - export_report - STEP_START - Started execution of step "export_report".
[32m2024-09-24 12:03:08 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Starting SodaAPI to Redshift Tables.....
[32m2024-09-24 12:03:08 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Fetching all datasets on page: 0
[32m2024-09-24 12:03:09 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Fetching all datasets on page: 1
[32m2024-09-24 12:03:09 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Fetching all datasets on page: 2
[32m2024-09-24 12:03:09 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Fetching all datasets on page: 3
[32m2024-09-24 12:03:10 +0200[0m - dagster - [34mINFO[0m - prod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - export_report - Fetching all checks on page 0
[32m2024-09-24 12:03:10 +0200[0m - dagster - [34mERROR[0m - [31mprod_pipeline - 2d5f4485-c974-4433-b035-3397e6d133b1 - 26231 - export_report - STEP_FAILURE - Execution of step "export_report" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "export_report"::

psycopg2.ProgrammingError: can't adapt type 'dict'

Stack Trace:
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/dbt-project/dagster/pipeline/exportapi.py", line 196, in export_report
    insert_into_table(conn, df_datasets, datasets_table)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/dbt-project/dagster/pipeline/exportapi.py", line 173, in insert_into_table
    cur.execute(insert_query, row)
[0m
